### ISSUE TITLE
Remove .idea directory and add it to .gitignore

### ISSUE THREAD

**Issue by armgabrielyan** [rkingrum/ForUsTheLiving#1]
When we use JetBrains IDEs, project specific settings are stored under .idea directory and change over time. This directory should be removed and added to .gitignore to avoid future inconveniences.

**Comment by robertLocarno** [comment]
@ArmenGabrielyan16 This is just my personal repo and isn't really maintained in any meaningful way, not sure you're commenting on the right one.
